### ISSUE TITLE
Question : pending on the weathermap host

### ISSUE THREAD

**Issue by Isnubi** [kozfelipe/centreon-weathermap#1]
Hello,
First of all, thanks for your plugin, it works so well!
But, I have a question. Is this normal that the weathermap host is always on pending status?

![image](https://user-images.githubusercontent.com/40593456/213940031-8607535a-e0ff-4ef4-93a2-e03599f3c6e4.png)

Thanks for your answer!

**Comment by kozfelipe** [comment]
Hi,
If you change from passive to active checks and setup a ping check for this host, it will become online, but this really doesn't change anything as the localhost always going to be online since its the own server.

**Comment by Isnubi** [comment]
Change to active checks and add base_alive_centreon command enable the host to not be pending !
I know that is don't really change anything but it is just to don't have a pending host on my global health of all my hosts up in Centreon.

ANSWER; Edit the `weathermap` host and add `generic-active-host-custom` to host templates to avoid having this host pending

Thanks for your quick answer!
