### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by Rico29** [kozfelipe/centreon-weathermap#2]
Hello
I installed your adapted weathermap in centreon, using php8.1

problem is that the created service "weathermap poller" calls the following command using centreon-engine user : 

php /usr/share/centreon/www/modules/centreon-weathermap/php/../poller.php

which results in errors : 

```
# sudo -u centreon-engine php  /usr/share/centreon/www/modules/centreon-weathermap/php/../poller.php
PHP Warning:  require(/etc/centreon/centreon.conf.php): Failed to open stream: Permission denied in /usr/share/centreon/config/centreon.config.php on line 40

Warning: require(/etc/centreon/centreon.conf.php): Failed to open stream: Permission denied in /usr/share/centreon/config/centreon.config.php on line 40
PHP Fatal error:  Uncaught Error: Failed opening required '/etc/centreon/centreon.conf.php' (include_path='.:/usr/share/php') in /usr/share/centreon/config/centreon.config.php:40
Stack trace:
#0 /usr/share/centreon/www/class/centreonDB.class.php(40): require_once()
#1 /usr/share/centreon/www/modules/centreon-weathermap/poller.php(10): require('...')
#2 {main}
  thrown in /usr/share/centreon/config/centreon.config.php on line 40

Fatal error: Uncaught Error: Failed opening required '/etc/centreon/centreon.conf.php' (include_path='.:/usr/share/php') in /usr/share/centreon/config/centreon.config.php:40
Stack trace:
#0 /usr/share/centreon/www/class/centreonDB.class.php(40): require_once()
#1 /usr/share/centreon/www/modules/centreon-weathermap/poller.php(10): require('...')
#2 {main}
  thrown in /usr/share/centreon/config/centreon.config.php on line 40

```

/usr/share/centreon/config/centreon.config.php tried to include  : 
 require _CENTREON_ETC_ . '/centreon.conf.php';

so I've set-up a crontab qhich generates the output images 

```
# tail /etc/cron.d/centreon -n2

# Cron for weathermaps generation
*/2 * * * * root php  /usr/share/centreon/www/modules/centreon-weathermap/php/../poller.php
```

but I still have warnings like : 

```
Deprecated: Function strftime() is deprecated in /usr/share/centreon/www/modules/centreon-weathermap/src/lib/Weathermap.class.php on line 3207
PHP Deprecated:  Implicit conversion from float 84.5 to int loses precision in /usr/share/centreon/www/modules/centreon-weathermap/src/lib/WeatherMapNode.class.php on line 640

Deprecated: Implicit conversion from float 84.5 to int loses precision in /usr/share/centreon/www/modules/centreon-weathermap/src/lib/WeatherMapNode.class.php on line 640
PHP Deprecated:  Implicit conversion from float 101.5 to int loses precision in /usr/share/centreon/www/modules/centreon-weathermap/src/lib/WeatherMapNode.class.php on line 640
```

**Comment by kozfelipe** [comment]
Hi @Rico29, seems your poller.php has not enough permissions to reach centreon.conf.php which grants weathermap access to the database. You may try to increase it using chmod, also, ensure these directories have write permission:
```
/usr/share/centreon/www/modules/centreon-weathermap/src/configs
/usr/share/centreon/www/modules/centreon-weathermap/src/output
/usr/share/centreon/www/modules/centreon-weathermap/src/images
```

you may ignore those deprecated warnings or omit them, prepending a @ operator

let me know if you managed to fix it by changing permissions

**Comment by Tolkyen** [comment]
Hello, I'm getting the same error messages as Rico29. I've made sure that these directories have write permissions
/usr/share/centreon/www/modules/centreon-weathermap/src/configs
/usr/share/centreon/www/modules/centreon-weathermap/src/output
/usr/share/centreon/www/modules/centreon-weathermap/src/images

**Comment by kozfelipe** [comment]
hi @Tolkyen, have you ensure centreon-engine is the owner of output directory?

**Comment by Tolkyen** [comment]
Yes, this is the current setting
![image](https://github.com/kozfelipe/centreon-weathermap/assets/22937749/559d50d9-2069-4795-8876-ed62242dce0f)

**Comment by kozfelipe** [comment]
@Tolkyen can you show how are permission settings for poller.php?

**Comment by Tolkyen** [comment]
![image](https://github.com/kozfelipe/centreon-weathermap/assets/22937749/66c299c2-e0a3-4edc-8536-c691be33a0ab)

**Comment by kozfelipe** [comment]
- I just removed my module and re-download it from this repo

- and I ran the following:

`sudo chown -R apache:apache /usr/share/centreon/www/modules/centreon-weathermap/`
`chown -R centreon-engine:apache /usr/share/centreon/www/modules/centreon-weathermap/src/output/`
`chmod 777 /usr/share/centreon/www/modules/centreon-weathermap/poller.php`

- reactivated the module from extension manager

- and ran `sudo -u centreon-engine /usr/share/centreon/www/modules/centreon-weathermap/poller.php`

I got the following output without errors:
`2024-03-04 18:48 - 0 processed`

![image](https://github.com/kozfelipe/centreon-weathermap/assets/25208457/eadb5019-a10a-4248-9359-f5041ad48b70)

can you confirm these steps?

I used php 8.1.12
`-rw-r--r-- 1 apache apache /etc/centreon/centreon.conf.php`

**Comment by Tolkyen** [comment]
Hi @kozfelipe, I followed your instructions. I've found the reason for the error: you need to add read access for others to the /etc/centreon/centreon.conf.php file..
This is less secure than what the centreon documentation recommends (https://docs.centreon.com/docs/23.04/administration/secure-platform/#securing-configuration-files).

Thank you for your help.

**Comment by kozfelipe** [comment]
Very well, I'm glad you made it
